### ISSUE TITLE
sudo make install error (iMac computer terminal install)

### ISSUE THREAD

**Issue by lcamVz** [kdmurray91/axe#17] opened 2022-07-15 23:14 UTC
Hi I am trying to install axe and am facing this error: 

```
[  3%] Building C object src/libqes/src/CMakeFiles/qes_static.dir/qes_compat.c.o
clang: error: no such file or directory: 'NOTFOUND'
make[2]: *** [src/libqes/src/CMakeFiles/qes_static.dir/qes_compat.c.o] Error 1
make[1]: *** [src/libqes/src/CMakeFiles/qes_static.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by kdm9** [comment] 2022-07-16 06:13
closing this issue as it's a duplicate of #15. Please continue the discussion there :)

**Closed as completed by kdm9** 2022-07-16 06:13 UTC
